USE smart_railway_db;

-- 1. Complete train route with station order, platforms and distances.
SELECT t.train_number, t.train_name, r.route_name, s.station_code, s.station_name,
       ts.stop_order, ts.arrival_time, ts.departure_time, ts.platform_number,
       ts.distance_from_source_km
FROM trains t
JOIN routes r ON r.train_id = t.train_id
JOIN train_schedule ts ON ts.route_id = r.route_id
JOIN stations s ON s.station_id = ts.station_id
WHERE t.train_number = '12951'
ORDER BY ts.stop_order;

-- 2. Delayed trains with current and next stations.
SELECT t.train_number, t.train_name, cur.station_name AS current_station,
       nxt.station_name AS next_station, lt.status, lt.delay_minutes
FROM live_tracking lt
JOIN trains t ON t.train_id = lt.train_id
LEFT JOIN stations cur ON cur.station_id = lt.current_station_id
LEFT JOIN stations nxt ON nxt.station_id = lt.next_station_id
WHERE lt.delay_minutes > 0
ORDER BY lt.delay_minutes DESC;

-- 3. Punctuality report grouped by train status.
SELECT status, COUNT(*) AS train_count, ROUND(AVG(delay_minutes), 2) AS average_delay
FROM live_tracking
GROUP BY status
ORDER BY train_count DESC;

-- 4. Revenue generated by every train.
SELECT t.train_number, t.train_name, COUNT(b.booking_id) AS tickets_booked,
       SUM(b.fare) AS total_revenue
FROM trains t
LEFT JOIN bookings b ON b.train_id = t.train_id
GROUP BY t.train_id, t.train_number, t.train_name
ORDER BY total_revenue DESC;

-- 5. Nested query: trains running on routes longer than the average route distance.
SELECT train_number, train_name
FROM trains
WHERE train_id IN (
    SELECT train_id
    FROM routes
    WHERE total_distance_km > (SELECT AVG(total_distance_km) FROM routes)
)
ORDER BY train_name;

-- 6. Platform load report by station.
SELECT s.station_code, s.station_name, ts.platform_number, COUNT(*) AS scheduled_trains
FROM train_schedule ts
JOIN stations s ON s.station_id = ts.station_id
GROUP BY s.station_code, s.station_name, ts.platform_number
ORDER BY scheduled_trains DESC, s.station_code;
